export interface ProductBySearch {
    _id? : any,
    title : string,
    price? : Number,
    images : string,
    aboutThis ?: any,
    description ?: string,
    feedback?: any,
    totalAvailableQuantity? : number,
    salePrice ?: any,
    specs? : any,
    variants? : any,
    ratings?: any,
    link?: String,
    firstVariant?: String,
    secondVariant?: String,
    thirdVariant?: String,
    fourthVariant?: String,
    quantity: Number,
}
